### ISSUE TITLE
[Question on functionality] How does auto build of orbital collectors work?

### ISSUE THREAD

**Issue by Chemie99** [soarqin/DSP_Mods#25]
I tried from the menu to press the quick build button (to enable)? but no effect in-game.
I tried with a 40 collector BP, opened the UI, and clicked "Quick build" (max) and nothing happened either.
How is this supposed to be enabled?

**Comment by soarqin** [comment]
You should have orbital collectors in your bag and be on a gas giant to make this functions working.
After clicking the `Quick build` button, you should see prebuilt collectors put on equator of Gas Giant. If there is no existing collectors, they are placed from (0°,0°), otherwise they will be placed right next to exsiting ones. You have to fly around equator to have them built using construction bots.
Note: Enable `Instant Build` in CheatEnabler will build collectors instantly without entering prebuild status.

**Comment by Chemie99** [comment]
OK.  Got it now.  I was placing the blueprint first thinking it would need the ghosts to build vs it placing and building. I thought its function was to insta-buld vs just placing the blueprint (which BlueprintTweaks does.
Thanks for the reply.
